---
- name: Configure Flask Application
  hosts: containers
  connection: docker
  tasks:
    - name: Create a config file inside container
      copy:
        content: |
          APP_NAME=Flask DevOps App
          VERSION=1.0
          ENVIRONMENT=development
        dest: /app/config.env

    - name: Check if config file was created
      command: cat /app/config.env
      register: config_content

    - name: Show the config file
      debug:
        msg: "{{ config_content.stdout }}"
